[build]
  command = "npm i && cd api && npm i && cd ../web-react && npm i && cd .. && npm run build && cp api/build/graphql-schema.js api/build/functions/graphql/. && cp api/build/schema.graphql api/build/functions/graphql/.  && cd api/src/functions/graphql && npm i"
  publish = "web-react/build"
  functions = "api/build/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 4001
  framework = "#custom"

[template.environment]
  NEO4J_URI = "bolt://3.86.228.230:7687"
  NEO4J_USER = "neo4j"
  NEO4J_PASSWORD = "arts-dyes-north"
  
[[redirects]]
  from = "/*"
  to = "/*"
  status = 200

[[redirects]]
  from = "/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
