import { typeDefs } from './graphql-schema'
import { ApolloServer } from 'apollo-server-express'
import express from 'express'
import neo4j from 'neo4j-driver'
import { Neo4jGraphQL } from '@neo4j/graphql'
import dotenv from 'dotenv'
import { initializeDatabase } from './initialize'
import jwt from 'express-jwt'
import { resolvers } from './resolvers'
// set environment variables from .env
dotenv.config()

const {
  JWT_SECRET,
  DEV_NEO4J_URI,
  DEV_NEO4J_USER,
  DEV_NEO4J_PASSWORD,
  PRODUCTION_NEO4J_URI,
  PRODUCTION_NEO4J_USER,
  PRODUCTION_NEO4J_PASSWORD,
  NEO4J_DATABASE,
  GRAPHQL_SERVER_PORT,
  GRAPHQL_SERVER_PATH,
  GRAPHQL_SERVER_HOST,
  NETLIFY_DEV,
} = process.env

const NEO4J_URI = NETLIFY_DEV ? DEV_NEO4J_URI : PRODUCTION_NEO4J_URI
const NEO4J_USER = NETLIFY_DEV ? DEV_NEO4J_USER : PRODUCTION_NEO4J_USER
const NEO4J_PASSWORD = NETLIFY_DEV
  ? DEV_NEO4J_PASSWORD
  : PRODUCTION_NEO4J_PASSWORD

const app = express()

app.use(
  jwt({
    secret: JWT_SECRET.replace(/\\n/gm, '\n'),
    algorithms: ['RS256'],
    credentialsRequired: false,
  })
)

/*
 * Create an executable GraphQL schema object from GraphQL type definitions
 * including autogenerated queries and mutations.
 * Optionally a config object can be included to specify which types to include
 * in generated queries and/or mutations. Read more in the docs:
 * https://grandstack.io/docs/neo4j-graphql-js-api.html#makeaugmentedschemaoptions-graphqlschema
 */

const driver = neo4j.driver(
  NEO4J_URI || 'bolt://localhost:7687',
  neo4j.auth.basic(NEO4J_USER || 'neo4j', NEO4J_PASSWORD || 'neo4j')
)

const neo4jGraphQL = new Neo4jGraphQL({
  driver,
  typeDefs,
  resolvers,
})

/*
 * Create a Neo4j driver instance to connect to the database
 * using credentials specified as environment variables
 * with fallback to defaults
 */

/*
 * Perform any database initialization steps such as
 * creating constraints or ensuring indexes are online
 *
 */
const init = async driver => {
  await initializeDatabase(driver)
}

/*
 * We catch any errors that occur during initialization
 * to handle cases where we still want the API to start
 * regardless, such as running with a read only user.
 * In this case, ensure that any desired initialization steps
 * have occurred
 */

init(driver)

/*
 * Create a new ApolloServer instance, serving the GraphQL schema
 * created using makeAugmentedSchema above and injecting the Neo4j driver
 * instance into the context object so it is available in the
 * generated resolvers to connect to the database.
 */
const server = new ApolloServer({
  context: ({ req }) => {
    return {
      driver,
      req,
      neo4jDatabase: NEO4J_DATABASE,
      cypherParams: {
        user: req?.user,
        userAuthId: req?.user?.sub,
      },
    }
  },
  schema: neo4jGraphQL.schema,
  introspection: true,
  playground: true,
})

// Specify host, port and path for GraphQL endpoint
const port = GRAPHQL_SERVER_PORT || 4001
const path = GRAPHQL_SERVER_PATH || '/graphql'
const host = GRAPHQL_SERVER_HOST || '0.0.0.0'

/*
 * Optionally, apply Express middleware for authentication, etc
 * This also also allows us to specify a path for the GraphQL endpoint
 */
server.applyMiddleware({ app, path })

app.listen({ host, port, path }, () => {
  console.log(`GraphQL server ready at http://${host}:${port}${path}`)
})
